/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#00228a",
        "error": "#ffb4ab",
        "surface-variant": "#353436",
        "on-secondary": "#3d2f00",
        "primary-fixed-dim": "#b9c3ff",
        "secondary-container": "#eebe01",
        "background": "#131314",
        "surface-container": "#201f20",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#584400",
        "on-error": "#690005",
        "secondary-fixed-dim": "#f1c109",
        "surface-bright": "#3a393a",
        "surface": "#131314",
        "error-container": "#93000a",
        "outline": "#8e90a1",
        "tertiary-container": "#595a5a",
        "inverse-surface": "#e5e2e3",
        "on-secondary-container": "#634e00",
        "tertiary-fixed-dim": "#c6c6c7",
        "tertiary-fixed": "#e2e2e2",
        "primary-fixed": "#dde1ff",
        "surface-container-low": "#1c1b1c",
        "secondary": "#ffdc7c",
        "primary-container": "#2249db",
        "on-tertiary-fixed": "#1a1c1c",
        "inverse-primary": "#294edf",
        "surface-container-lowest": "#0e0e0f",
        "on-primary-container": "#c8cfff",
        "surface-tint": "#b9c3ff",
        "inverse-on-surface": "#313031",
        "on-surface-variant": "#c4c5d8",
        "surface-container-highest": "#353436",
        "on-surface": "#e5e2e3",
        "surface-container-high": "#2a2a2b",
        "on-primary-fixed": "#001257",
        "on-primary-fixed-variant": "#0033c0",
        "on-tertiary-container": "#d1d2d2",
        "surface-dim": "#131314",
        "on-tertiary": "#2f3131",
        "secondary-fixed": "#ffe08b",
        "on-background": "#e5e2e3",
        "primary": "#b9c3ff",
        "tertiary": "#c6c6c7",
        "outline-variant": "#444655",
        "on-secondary-fixed": "#241a00",
        "on-tertiary-fixed-variant": "#454747"
      },
      fontFamily: {
        "headline": ["Epilogue"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Plus Jakarta Sans"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
