create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  location text,
  rating integer not null default 5,
  message text not null,
  status text not null default 'pending',
  admin_notes text,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint feedback_rating_check check (rating between 1 and 5),
  constraint feedback_status_check check (status in ('pending', 'accepted', 'rejected'))
);

create index if not exists idx_feedback_status_submitted_at
  on public.feedback (status, submitted_at desc);

drop trigger if exists trg_feedback_updated_at on public.feedback;
create trigger trg_feedback_updated_at
before update on public.feedback
for each row
execute function public.set_row_updated_at();

alter table public.feedback enable row level security;

drop policy if exists "service role full access feedback" on public.feedback;
create policy "service role full access feedback"
on public.feedback
for all
to service_role
using (true)
with check (true);

drop policy if exists "anon can submit feedback" on public.feedback;
create policy "anon can submit feedback"
on public.feedback
for insert
to anon
with check (status = 'pending');

drop policy if exists "anon can read accepted feedback" on public.feedback;
create policy "anon can read accepted feedback"
on public.feedback
for select
to anon
using (status = 'accepted');
