set check_function_bodies = off;

create extension if not exists citext with schema public;
create extension if not exists pg_trgm with schema public;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'admin_role_enum') then
    create type public.admin_role_enum as enum ('admin', 'main_admin');
  end if;

  if not exists (select 1 from pg_type where typname = 'enquiry_type_enum') then
    create type public.enquiry_type_enum as enum ('cab', 'room', 'tour', 'custom', 'general');
  end if;

  if not exists (select 1 from pg_type where typname = 'enquiry_status_enum') then
    create type public.enquiry_status_enum as enum (
      'New',
      'Contacted',
      'Quoted',
      'Awaiting Customer',
      'Assigned',
      'Confirmed',
      'Completed',
      'Rejected',
      'Cancelled'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'enquiry_priority_enum') then
    create type public.enquiry_priority_enum as enum ('Low', 'Normal', 'High', 'Urgent');
  end if;

  if not exists (select 1 from pg_type where typname = 'contact_method_enum') then
    create type public.contact_method_enum as enum ('whatsapp', 'phone', 'email');
  end if;

  if not exists (select 1 from pg_type where typname = 'notification_status_enum') then
    create type public.notification_status_enum as enum ('not_enabled', 'pending', 'sent', 'failed');
  end if;

  if not exists (select 1 from pg_type where typname = 'driver_status_enum') then
    create type public.driver_status_enum as enum ('Active', 'Unavailable', 'Inactive');
  end if;

  if not exists (select 1 from pg_type where typname = 'driver_licence_status_enum') then
    create type public.driver_licence_status_enum as enum ('Pending', 'Verified', 'Expired');
  end if;

  if not exists (select 1 from pg_type where typname = 'fleet_status_enum') then
    create type public.fleet_status_enum as enum ('Available', 'On Trip', 'Maintenance');
  end if;

  if not exists (select 1 from pg_type where typname = 'fleet_condition_enum') then
    create type public.fleet_condition_enum as enum ('Excellent', 'Good', 'Needs Attention');
  end if;

  if not exists (select 1 from pg_type where typname = 'insurance_status_enum') then
    create type public.insurance_status_enum as enum ('Unknown', 'Valid', 'Expiring Soon', 'Expired');
  end if;
end
$$;

create or replace function public.set_row_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.generate_enquiry_reference_id()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  reference_prefix text;
  reference_year integer;
  next_sequence integer;
begin
  if new.reference_id is not null and btrim(new.reference_id) <> '' then
    return new;
  end if;

  reference_prefix := case new.enquiry_type
    when 'cab' then 'CAB'
    when 'room' then 'ROOM'
    when 'tour' then 'TOUR'
    when 'custom' then 'CUSTOM'
    else 'GEN'
  end;

  reference_year := extract(year from coalesce(new.submitted_at, now()))::integer;

  insert into public.enquiry_counters (enquiry_type, enquiry_year, last_number)
  values (new.enquiry_type, reference_year, 1)
  on conflict (enquiry_type, enquiry_year)
  do update set last_number = public.enquiry_counters.last_number + 1
  returning last_number into next_sequence;

  new.reference_id := reference_prefix || '-' || reference_year || '-' || lpad(next_sequence::text, 4, '0');
  return new;
end;
$$;

create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  email public.citext not null,
  password text not null,
  role public.admin_role_enum not null default 'admin',
  is_main_admin boolean not null default false,
  reset_token text,
  reset_token_expiry timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admins_email_key unique (email)
);

create table if not exists public.admin_setup_keys (
  id bigint generated by default as identity primary key,
  token_hash text not null,
  created_by bigint references public.admins(id) on delete set null,
  expires_at timestamptz not null,
  used boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fleet (
  id text primary key,
  model text not null,
  plate text not null,
  type text,
  status public.fleet_status_enum not null default 'Available',
  "lastService" date,
  photo text,
  age integer not null default 0,
  fuel_status integer not null default 100,
  next_service date,
  condition public.fleet_condition_enum not null default 'Good',
  notes text,
  insurance_provider text,
  insurance_policy text,
  insurance_start date,
  insurance_expiry date,
  insurance_status public.insurance_status_enum not null default 'Unknown',
  insurance_doc text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fleet_plate_key unique (plate),
  constraint fleet_age_check check (age >= 0),
  constraint fleet_fuel_status_check check (fuel_status between 0 and 100),
  constraint fleet_service_window_check check (
    insurance_start is null or insurance_expiry is null or insurance_expiry >= insurance_start
  )
);

create table if not exists public.drivers (
  id text primary key,
  name text not null,
  phone text,
  rating text not null default '5.0',
  experience text,
  status public.driver_status_enum not null default 'Active',
  photo text,
  licence_status public.driver_licence_status_enum not null default 'Pending',
  address text,
  notes text,
  assigned_vehicle text references public.fleet(id) on delete set null on update cascade,
  total_rides integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint drivers_total_rides_check check (total_rides >= 0)
);

create table if not exists public.enquiry_counters (
  enquiry_type public.enquiry_type_enum not null,
  enquiry_year integer not null,
  last_number integer not null default 0,
  primary key (enquiry_type, enquiry_year),
  constraint enquiry_counters_year_check check (enquiry_year between 2000 and 9999),
  constraint enquiry_counters_last_number_check check (last_number >= 0)
);

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  reference_id text not null,
  enquiry_type public.enquiry_type_enum not null default 'general',
  customer_name text not null,
  phone_number text not null,
  whatsapp_number text,
  email text,
  preferred_contact_method public.contact_method_enum not null default 'whatsapp',
  source_page text,
  status public.enquiry_status_enum not null default 'New',
  priority public.enquiry_priority_enum not null default 'Normal',
  travel_date date,
  travel_time text,
  service_details_json jsonb not null default '{}'::jsonb,
  admin_notes text,
  assigned_driver_id text references public.drivers(id) on delete set null on update cascade,
  assigned_vehicle_id text references public.fleet(id) on delete set null on update cascade,
  assigned_room_id text,
  assigned_package_id text,
  assigned_hotel_option text,
  assigned_owner_id text,
  quote_amount text,
  consent_to_contact boolean not null default true,
  requirement_notes text,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_contacted_at timestamptz,
  follow_up_at timestamptz,
  is_archived boolean not null default false,
  archived_at timestamptz,
  archived_reason text,
  admin_whatsapp_notification_status public.notification_status_enum not null default 'not_enabled',
  customer_whatsapp_notification_status public.notification_status_enum not null default 'not_enabled',
  whatsapp_error_message text,
  notification_sent_at timestamptz,
  notification_status public.notification_status_enum not null default 'pending',
  notification_error text,
  constraint enquiries_reference_id_key unique (reference_id),
  constraint enquiries_reference_id_format_check check (reference_id ~ '^[A-Z]+-[0-9]{4}-[0-9]{4}$'),
  constraint enquiries_archive_consistency_check check (
    (is_archived = false and archived_at is null)
    or (is_archived = true)
  )
);

create table if not exists public.cab_enquiry_details (
  enquiry_id bigint primary key references public.enquiries(id) on delete cascade,
  pickup text,
  dropoff text,
  passengers integer,
  luggage text,
  vehicle_preference text,
  requirement_notes text,
  constraint cab_enquiry_details_passengers_check check (passengers is null or passengers >= 0)
);

create table if not exists public.room_enquiry_details (
  enquiry_id bigint primary key references public.enquiries(id) on delete cascade,
  check_in date,
  check_out date,
  guests integer,
  room_count integer,
  room_type text,
  budget text,
  preferred_area text,
  preferred_hotel text,
  constraint room_enquiry_details_guest_count_check check (guests is null or guests >= 0),
  constraint room_enquiry_details_room_count_check check (room_count is null or room_count >= 0),
  constraint room_enquiry_details_date_range_check check (
    check_in is null or check_out is null or check_out >= check_in
  )
);

create table if not exists public.tour_enquiry_details (
  enquiry_id bigint primary key references public.enquiries(id) on delete cascade,
  destination text,
  travel_window_start date,
  travel_window_end date,
  duration_days integer,
  group_size integer,
  pickup_required text,
  hotel_preference text,
  budget text,
  constraint tour_enquiry_details_duration_check check (duration_days is null or duration_days >= 0),
  constraint tour_enquiry_details_group_size_check check (group_size is null or group_size >= 0),
  constraint tour_enquiry_details_date_range_check check (
    travel_window_start is null or travel_window_end is null or travel_window_end >= travel_window_start
  )
);

create table if not exists public.custom_trip_details (
  enquiry_id bigint primary key references public.enquiries(id) on delete cascade,
  custom_category text,
  location text,
  travel_window_start date,
  travel_window_end date,
  group_size integer,
  budget text,
  requirement_notes text,
  constraint custom_trip_details_group_size_check check (group_size is null or group_size >= 0),
  constraint custom_trip_details_date_range_check check (
    travel_window_start is null or travel_window_end is null or travel_window_end >= travel_window_start
  )
);

create table if not exists public.enquiry_audit_log (
  id bigint generated by default as identity primary key,
  enquiry_id bigint not null references public.enquiries(id) on delete cascade,
  admin_id bigint references public.admins(id) on delete set null,
  admin_role public.admin_role_enum,
  action_type text not null,
  field_name text,
  previous_value text,
  next_value text,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_admin_setup_keys_active
  on public.admin_setup_keys (used, expires_at desc);

create index if not exists idx_drivers_status
  on public.drivers (status);

create index if not exists idx_drivers_assigned_vehicle
  on public.drivers (assigned_vehicle);

create index if not exists idx_fleet_status
  on public.fleet (status);

create index if not exists idx_fleet_insurance_expiry
  on public.fleet (insurance_expiry);

create index if not exists idx_enquiries_type_status
  on public.enquiries (enquiry_type, status);

create index if not exists idx_enquiries_submitted_at
  on public.enquiries (submitted_at desc);

create index if not exists idx_enquiries_travel_date
  on public.enquiries (travel_date);

create index if not exists idx_enquiries_is_archived
  on public.enquiries (is_archived);

create index if not exists idx_enquiries_assigned_driver_id
  on public.enquiries (assigned_driver_id);

create index if not exists idx_enquiries_assigned_vehicle_id
  on public.enquiries (assigned_vehicle_id);

create index if not exists idx_enquiries_assigned_room_id
  on public.enquiries (assigned_room_id);

create index if not exists idx_enquiries_assigned_package_id
  on public.enquiries (assigned_package_id);

create index if not exists idx_enquiries_source_page
  on public.enquiries (source_page);

create index if not exists idx_enquiries_customer_name_trgm
  on public.enquiries using gin (lower(customer_name) gin_trgm_ops);

create index if not exists idx_enquiries_phone_number_trgm
  on public.enquiries using gin (lower(phone_number) gin_trgm_ops);

create index if not exists idx_enquiries_whatsapp_number_trgm
  on public.enquiries using gin (lower(coalesce(whatsapp_number, '')) gin_trgm_ops);

create index if not exists idx_enquiries_reference_id_trgm
  on public.enquiries using gin (lower(reference_id) gin_trgm_ops);

create index if not exists idx_enquiry_audit_log_enquiry_created
  on public.enquiry_audit_log (enquiry_id, created_at desc);

create index if not exists idx_enquiry_audit_log_admin_created
  on public.enquiry_audit_log (admin_id, created_at desc);

drop trigger if exists trg_admins_updated_at on public.admins;
create trigger trg_admins_updated_at
before update on public.admins
for each row
execute function public.set_row_updated_at();

drop trigger if exists trg_admin_setup_keys_updated_at on public.admin_setup_keys;
create trigger trg_admin_setup_keys_updated_at
before update on public.admin_setup_keys
for each row
execute function public.set_row_updated_at();

drop trigger if exists trg_drivers_updated_at on public.drivers;
create trigger trg_drivers_updated_at
before update on public.drivers
for each row
execute function public.set_row_updated_at();

drop trigger if exists trg_fleet_updated_at on public.fleet;
create trigger trg_fleet_updated_at
before update on public.fleet
for each row
execute function public.set_row_updated_at();

drop trigger if exists trg_enquiries_updated_at on public.enquiries;
create trigger trg_enquiries_updated_at
before update on public.enquiries
for each row
execute function public.set_row_updated_at();

drop trigger if exists trg_generate_enquiry_reference_id on public.enquiries;
create trigger trg_generate_enquiry_reference_id
before insert on public.enquiries
for each row
execute function public.generate_enquiry_reference_id();

alter table public.admins enable row level security;
alter table public.admin_setup_keys enable row level security;
alter table public.fleet enable row level security;
alter table public.drivers enable row level security;
alter table public.enquiry_counters enable row level security;
alter table public.enquiries enable row level security;
alter table public.cab_enquiry_details enable row level security;
alter table public.room_enquiry_details enable row level security;
alter table public.tour_enquiry_details enable row level security;
alter table public.custom_trip_details enable row level security;
alter table public.enquiry_audit_log enable row level security;

create policy "service role full access admins"
on public.admins
for all
to service_role
using (true)
with check (true);

create policy "service role full access admin_setup_keys"
on public.admin_setup_keys
for all
to service_role
using (true)
with check (true);

create policy "service role full access fleet"
on public.fleet
for all
to service_role
using (true)
with check (true);

create policy "service role full access drivers"
on public.drivers
for all
to service_role
using (true)
with check (true);

create policy "service role full access enquiry_counters"
on public.enquiry_counters
for all
to service_role
using (true)
with check (true);

create policy "service role full access enquiries"
on public.enquiries
for all
to service_role
using (true)
with check (true);

create policy "service role full access cab_enquiry_details"
on public.cab_enquiry_details
for all
to service_role
using (true)
with check (true);

create policy "service role full access room_enquiry_details"
on public.room_enquiry_details
for all
to service_role
using (true)
with check (true);

create policy "service role full access tour_enquiry_details"
on public.tour_enquiry_details
for all
to service_role
using (true)
with check (true);

create policy "service role full access custom_trip_details"
on public.custom_trip_details
for all
to service_role
using (true)
with check (true);

create policy "service role full access enquiry_audit_log"
on public.enquiry_audit_log
for all
to service_role
using (true)
with check (true);

create policy "anon can insert enquiries"
on public.enquiries
for insert
to anon, authenticated
with check (
  status = 'New'
  and is_archived = false
  and consent_to_contact = true
);
